apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 5
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-default-jy-web-admin
  managedFields:
  name: jy-web-admin
  namespace: default
  resourceVersion: "298491"
  selfLink: /apis/apps/v1/namespaces/default/deployments/jy-web-admin
  uid: 36796a69-658c-41d1-b244-272050ec279b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-jy-web-admin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":80,"dnsName":"jy-web-admin-nodeport","hostPort":0,"kind":"NodePort","name":"80tcp1","protocol":"TCP"}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-jy-web-admin
    spec:
      containers:
      - image: registry.cn-shenzhen.aliyuncs.com/bandex_stage/jy_web_admin:latest
        imagePullPolicy: Always
        name: jy-web-admin
        ports:
        - containerPort: 80
          name: 80tcp1
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: alihub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
